### PR TITLE
Implement multiple game folder support 

### PR DESCRIPTION
**Pull request by Ishan09811**
After fixing bunch of bugs it should be squash merge.

### CODE REVIEW

**Comment by Ishan09811** [comment]
@rtiangha 
Can you disable the workflow for this pr as it is in wip for now

**Comment by Ishan09811** [comment]
@rtiangha 
Screenshot_20241208-155432

**Comment by rtiangha** [comment]
On my S21, tapping on Search Locations looks like this.

**Comment by Ishan09811** [comment]
> On my S21, tapping on Search Locations looks like this.

@rtiangha 
Yeah because I need to setInsets correctly btw you have any platform where can I contact you directly so we discuss about it more better

**Comment by rtiangha** [comment]
Mastadon works.

[@regtiangha@mstdn.ca](https://mstdn.ca/@regtiangha)

**Comment by Ishan09811** [comment]
@rtiangha 
Unable to create account on mastadon I think they are not accepting new registrations for now

**Comment by Ishan09811** [comment]
> Mastadon works.
> 
> [@regtiangha@mstdn.ca](https://mstdn.ca/@regtiangha)

@rtiangha 

Finally successfully I opened an account but how can I DM you ? there was no option for it

**Comment by rtiangha** [comment]
My feedback:

* Please fix these errors:
```
/home/runner/work/Borked3DS/Borked3DS/src/android/app/src/main/res/values-de/strings.xml:20: Error: "select_games_folder" is translated here but not found in default locale [ExtraTranslation]
    <string name="select_games_folder">Spieleordner auswählen</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Borked3DS/Borked3DS/src/android/app/src/main/res/values-es/strings.xml:26: Error: "select_games_folder" is translated here but not found in default locale [ExtraTranslation]
    <string name="select_games_folder">Seleccionar Directorio de Juego</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Borked3DS/Borked3DS/src/android/app/src/main/res/values-fr/strings.xml:26: Error: "select_games_folder" is translated here but not found in default locale [ExtraTranslation]
    <string name="select_games_folder">Sélectionner le dossier des jeux</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Borked3DS/Borked3DS/src/android/app/src/main/res/values-pt/strings.xml:26: Error: "select_games_folder" is translated here but not found in default locale [ExtraTranslation]
    <string name="select_games_folder">Selecione a pasta de jogos</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Borked3DS/Borked3DS/src/android/app/src/main/res/values-ru/strings.xml:26: Error: "select_games_folder" is translated here but not found in default locale [ExtraTranslation]
    <string name="select_games_folder">Выбор папки с играми</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Borked3DS/Borked3DS/src/android/app/src/main/res/values-zh/strings.xml:26: Error: "select_games_folder" is translated here but not found in default locale [ExtraTranslation]
    <string name="select_games_folder">选择游戏文件夹</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Borked3DS/Borked3DS/src/android/app/src/main/res/values-es/strings.xml:27: Error: "select_games_folder_description" is translated here but not found in default locale [ExtraTranslation]
    <string name="select_games_folder_description">Permite que Borked3DS llene la lista de juegos</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Borked3DS/Borked3DS/src/android/app/src/main/res/values-fr/strings.xml:27: Error: "select_games_folder_description" is translated here but not found in default locale [ExtraTranslation]
    <string name="select_games_folder_description">Permet à Borked3DS de remplir la liste des jeux</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Borked3DS/Borked3DS/src/android/app/src/main/res/values-pt/strings.xml:27: Error: "select_games_folder_description" is translated here but not found in default locale [ExtraTranslation]
    <string name="select_games_folder_description">Permitir que o Borked3DS preencha a lista de jogos</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Borked3DS/Borked3DS/src/android/app/src/main/res/values-ru/strings.xml:27: Error: "select_games_folder_description" is translated here but not found in default locale [ExtraTranslation]
    <string name="select_games_folder_description">Позволяет Borked3DS формировать список игр</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Borked3DS/Borked3DS/src/android/app/src/main/res/values-zh/strings.xml:27: Error: "select_games_folder_description" is translated here but not found in default locale [ExtraTranslation]
    <string name="select_games_folder_description">允许 Borked3DS 填充游戏列表</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
(basically just delete the strings from the translations since they no longer exist in the main program)
* Please add a description for the **Search Locations** section
* If I delete all the game folders, stuff still appears in the search section and game section. It doesn't fully refresh until I restart the app. It's not a big deal in the grand scheme of things, but it did confuse me a bit. If there's any way to trigger a refresh whenever you tap away from settings or change the screen, that'd be great. If not, maybe a warning to the user would be useful.

**Comment by Ishan09811** [comment]
@rtiangha 

Done now it will reload games when a new location added or delated and also removed old strings

**Comment by rtiangha** [comment]
LGTM. Thanks!

**Pull request merged**
