### PR TITLE
Android: Fix crashes caused by tracy updates

### PR DESCRIPTION
**Pull request by Gamer64ytb**
By some time ago, I noticed that Borked3DS isn't opening on android, and I have found on mandarine that tracy is the reason of this.

Maybe just downgrading tracy isn't a very nice fix, but you can take it as a temp workaround I guess.

Leaving as draft fn because I need to test still what version is the faulty.

### CODE REVIEW

**Comment by rtiangha** [comment]
Opens just fine on my end. Is the problem still occurring now? And what version of Tracy is in this PR?

**Comment by nice-try-silly** [comment]
Doesn't open on my phone either. (OPPO Find X5 Lite, ColorOS 13.1)

**Comment by kleidis** [comment]
Can confirm it also crashes instantly for me on Android 14 (OneUI 6.1) and a Galaxy A34

**Comment by rtiangha** [comment]
Are people using the latest release? Can people submit logs? And does the build artifact from this PR open?

**Comment by kleidis** [comment]
> Are people using the latest release?

Latest ci build
 
 > Has any release from this fork ever worked?
 
 According to @Gamer64ytb nope
 
  > Can people submit logs? 
 
  I checked with logcat, its tracy
  
  ```
  2024-12-02 16:47:13.769 12428-12428 DEBUG                   pid-12428                            A  Cmdline: io.github.borked3ds.android.debug
2024-12-02 16:47:13.769 12428-12428 DEBUG                   pid-12428                            A  pid: 12391, tid: 12391, name: s.android.debug  >>> io.github.borked3ds.android.debug <<<
2024-12-02 16:47:13.769 12428-12428 DEBUG                   pid-12428                            A        #03 pc 000000000220b8b8  /data/app/~~lu8xN5IcBi6oaWBVPFaDDQ==/io.github.borked3ds.android.debug-5d-aiy7zKW_bybozpMNBhg==/lib/arm64/libborked3ds-android.so (tracy::Profiler::ReportTopology()+464) (BuildId: 93e24f7dd6556975cdd101354b0f5a3615dbf39b)
2024-12-02 16:47:13.769 12428-12428 DEBUG                   pid-12428                            A        #04 pc 000000000220ae44  /data/app/~~lu8xN5IcBi6oaWBVPFaDDQ==/io.github.borked3ds.android.debug-5d-aiy7zKW_bybozpMNBhg==/lib/arm64/libborked3ds-android.so (tracy::Profiler::Profiler()+832) (BuildId: 93e24f7dd6556975cdd101354b0f5a3615dbf39b)
2024-12-02 16:47:13.769 12428-12428 DEBUG                   pid-12428                            A        #05 pc 000000000220a7b4  /data/app/~~lu8xN5IcBi6oaWBVPFaDDQ==/io.github.borked3ds.android.debug-5d-aiy7zKW_bybozpMNBhg==/lib/arm64/libborked3ds-android.so (BuildId: 93e24f7dd6556975cdd101354b0f5a3615dbf39b)
2024-12-02 16:47:15.238 12478-12478 DEBUG                   pid-12478                            A  Cmdline: io.github.borked3ds.android.debug
```
 
  > And does the build artifact from this PR open?

He didn't turn on actions on his fork, l'll have to compile it on my own

**Comment by rtiangha** [comment]
Right. Well, I just turned it on here so something should be ready in an hour or two. If they could provide the Tracy version included in this PR, it'd at least help in bisecting Tracy's commits to see what's going on. Another thing to try is setting the cmake option to disable compiling Tracy to begin with and see if that helps.

**Comment by rtiangha** [comment]
OK, here are a couple more Android builds to test.

This one does not have Tracy included (i.e. ENABLE_PROFILING=OFF):
https://github.com/rtiangha/Borked3DS/actions/runs/12134141471

And this one has Tracy updated to HEAD to see if they fixed whatever the problem is (it doesn't build under msys2 though, but that's not what's being tested here so it doesn't matter right now):
https://github.com/rtiangha/Borked3DS/actions/runs/12133768728

Does the problem still occur under either build?

**Comment by Gamer64ytb** [comment]
> OK, here are a couple more Android builds to test.
> 
> This one does not have Tracy included (i.e. ENABLE_PROFILING=OFF): https://github.com/rtiangha/Borked3DS/actions/runs/12134141471
> 
> And this one has Tracy updated to HEAD to see if they fixed whatever the problem is (it doesn't build under msys2 though, but that's not what's being tested here so it doesn't matter right now): https://github.com/rtiangha/Borked3DS/actions/runs/12133768728
> 
> Does the problem still occur under either build?

The first build is no longer crashing here. :)

**Comment by Ishan09811** [comment]
> OK, here are a couple more Android builds to test.
> 
> This one does not have Tracy included (i.e. ENABLE_PROFILING=OFF): https://github.com/rtiangha/Borked3DS/actions/runs/12134141471
> 
> And this one has Tracy updated to HEAD to see if they fixed whatever the problem is (it doesn't build under msys2 though, but that's not what's being tested here so it doesn't matter right now): https://github.com/rtiangha/Borked3DS/actions/runs/12133768728
> 
> Does the problem still occur under either build?

Disabled Tracy build is working

**Comment by rtiangha** [comment]
> Disabled Tracy build is working but the ui is little broken 

Yeah, hence the name of the project. Merging in incomplete or not rigorously tested PRs is probably part of it. I didn't want to open up things too much until they were tackled, but PRs with fixes welcome I guess.

**Comment by rtiangha** [comment]
For those with the Android Tracy issues, does this build help?

https://github.com/rtiangha/Borked3DS/actions/runs/12225953814

**Comment by kleidis** [comment]
Works on my end

**Comment by rtiangha** [comment]
So does it solve the issue? If so, then this PR can be closed.

**Comment by kleidis** [comment]
@Gamer64ytb close the pr

**Comment by Gamer64ytb** [comment]
All seems fixed now. Nice 💪

**Comment by rtiangha** [comment]
@Gamer64ytb Thanks for the heads up!

For those who were curious, the issue was fixed in Tracy HEAD but HEAD also breaks Tracy on msys2 so the fix on this end was to take the last major release version and patch in the one commit that fixed the Android issues. Hopefully when they do their next major release, the msys2 issues will be fixed too and we won't have to maintain a custom patched version on this end.

**Pull request closed without merging**
